language: rust
dist: trusty
sudo: false
cache: cargo
os:
  - linux
  - osx
rust:
  - nightly
install:
    # Required for Racer autoconfiguration
    rustup component add rust-src
script:
  # compile #[cfg(not(test))] code
  - cargo build --verbose
  - cargo test --verbose
